docs/SyntaxForModels.md

It's a minor clarification, I know, but when I read this part of the documentation, I thought to myself "That's a weird way for comments to work"... but when I tested it, comments work exactly as you would expect, just the description seems a little weird.
The existing description implies that a `#` anywhere on a line will comment that entire line.  This change clarifies that a `#` will only comment the rest of the line following the `#`

Clarify how comments work

---

docs/Adapters.md

The documentation incorrectly showed that casbin was the author of the etcd adapter, despite it actually being implemented by another developer. This is appearance as the repository isn't in the casbin organization. I merely updated the text to link to the author.

Updated Adapters.md to fix accreditation for etcd adapter

---

docs/ManagementAPI.md

It is because I forgot to add the end-tag. Sorry, it won't happen again.

Adding end tag for avoiding other tab collapse.

---

docs/Adapters.md

At Touchify, we use Casbin for access control over our API.
We allows users to manage their own access control on their projects so we manage a very big policies database.
With this in mind, we built a "native" PostgreSQL adapter for Casbin with improved performances and advanced policy filtering.
Here are the advanced filters:
```typescript
// Load the filtered policy from DB.
await e.loadFilteredPolicy({
p: ["regex:(role:.*)|(alice)"],
g: ["", "like:role:%"]
});
```
**Details:**
* `like:` prefix: generates a `WHERE` clause using `LIKE` operator on PostgreSQL
* `regex:` prefix: generates a `WHERE` clause using `~` (regex) operator on PostgreSQL
It allows us to only query the necessaries policies to evaluate the right to increase the evaluation performances.
We hope that this adapter will …

Add new PostgreSQL adapter for node-casbin

---

website/static/css/docusaurus-admonitions.css

In Reference to #87 
On going through the code. The previous rule of css left aligned the heading so, I overide the rule may be it helpful.

Add the css to make the heading at centre

---

website/static/css/code-blocks-buttons.css

fix: Show hidden back-to-top button.

---

docs/Adapters.md

[sqlx-adapter](https://github.com/Blank-Xu/sqlx-adapter) is a new adapter for casbin write in go. 
She has been tested in most databases.
MySQL, PostgreSQL, MsSql, SQLite3 are supported in master branch and Oracle is supported in oracle branch.

Add Sqlx Adapter for go

---

docs/Overview.md

Minor change typo (explicit instead of explict) in What Casbin does: line four (4).

Fix typo in Overview.md

---

website/static/css/docusaurus-admonitions.css

Fix: https://github.com/casbin/casbin-website/issues/227
changed the brand name hover features as follow:
1. Removed the underline text decoration
2. On hover, the color won't change, instead only the cursor changes to pointer

fix: Brand name looks changed

---

docs/Benchmark.md

Signed-off-by: Yash Pandey (YP) <yash.btech.cs19@iiitranchi.ac.in>
---
Added benchmarks for [casbin-cpp](https://github.com/casbin/casbin-cpp) as per the discussion in casbin/casbin-cpp#118.

feat: Added benchmarks for Casbin-CPP

---

docs/Adapters.md

Adds [casbin-tortoise-adapter](https://github.com/thearchitector/casbin-tortoise-adapter) for AsyncCasbin to the list of 3rd party adapters.

docs: Add Tortoise ORM adapter

---

docs/Adapters.md
docs/GetStarted.md

Since we already have `casbin` module in path from LuaRocks, we don't need to add it separately in `package.path`. Also, this makes the formatting a bit more consistent.

fix: Lua Casbin docs and formatting and added Lua Casbin adapters

---

docs/Adapters.md

I would be thrilled if you could add my package to your list of adapters. The package is a storage adapter to support fs.FS and embed.FS.

docs: add fs.FS adapter to docs

---

.github/workflows/node-ci.yml

As CI use container to build, add safe directory out of the container is useless and can be removed

Remove `add safe` step

---

docs/RBACAPI.md

This PR add missing Go code snippets for these methods on RBAC API:
- AddRolesForUser
- AddPermissionsForUser
It fixes one item of issue #306

feat: Updating RBAC API Go code examples #306

---

docs/ManagementAPI.md

This PR add missing Python code snippets on Management API for these methods:
- GetAllSubjects
- GetAllNamedSubjects
- GetAllObjects
- GetAllNamedObjects
- GetAllActions
- GetAllNamedActions
- GetAllRoles
- GetAllNamedRoles
- GetPolicy
- GetFilteredPolicy
-  GetNamedPolicy
- GetFilteredNamedPolicy
- GetGroupingPolicy
-  GetFilteredGroupingPolicy 
- GetNamedGroupingPolicy
-  GetFilteredNamedGroupingPolicy

feat: Add missing python code examples for get methods

---

docs/ManagementAPI.md

This PR add missing Python code snippets on Management API for these methods:
- HasPolicy
- HasNamedPolicy
- AddPolicy
- AddPolicies
- AddNamedPolicy
- AddNamedPolicies
- RemovePolicy
- RemovePolicies
- RemoveFilteredPolicy
- RemoveNamedPolicy
- RemoveNamedPolicies
- RemoveFilteredNamedPolicy
- HasGroupingPolicy
- HasNamedGroupingPolicy
- AddGroupingPolicy
- AddGroupingPolicies
- AddNamedGroupingPolicy
- AddNamedGroupingPolicies
- RemoveGroupingPolicy
- RemoveGroupingPolicies
- RemoveFilteredGroupingPolicy
- RemoveNamedGroupingPolicy
- RemoveNamedGroupingPolicies
- RemoveFilteredNamedGroupingPolicy

feat: Add missing python code examples for add, has and remove methods

---

docs/RBACAPI.md

This PR add missing Python code snippets on RBAC API for these methods:
- getRolesForUser
- getUsersForRole
- getPermissionsForUser
- getImplicitRolesForUser
- getImplicitPermissionsForUser

Add missing python code get examples for RBAC API

---

docs/RBACAPI.md

This PR add missing Python code snippets on RBAC API for these methods:
- hasRoleForUser
- addRoleForUser
- deleteRoleForUser
- deleteRolesForUser
- deleteUser
- deleteRole
- deletePermission
- deletePermissionForUser
- deletePermissionsForUser
- hasPermissionForUser

feat: Add python code examples for nonget rbac api methods

---

docs/RBACWithDomainsAPI.md

This PR add missing Python code snippets on RBAC API for these methods:
- getRolesForUserInDomain
- getUsersForRoleInDomain
- AddRoleForUserInDomain
and fix enforcer example to read rbac_with_domains configuration policy

fix: Update RBACWithDomainsAPI python code examples and fix enforcer examples

---

docs/ManagementAPI.md

This PR add missing Python code snippets on Management API for these methods:
- updatePolicy
- updatePolicies

feat: Add update_policy python code examples

---

docs/GraphQLMiddlewares.md

The goal of this change is to add a reference to [`graphql-authz`](https://github.com/Checho3388/graphql-authz) middleware written in Python.

Add reference to new GraphQL middleware in Python

---

docs/RoleManagerApi.md

This PR adds  python code snippet on RoleManager API docs page for following methods:
- getRoleManager
- getUsers
- getRoles

feat: Add roleManager python examples for get methods

---

docs/Overview.md

Minor change typo (Elixir instead of Exilir) in Overview.md
Signed-off-by: BSS ZU <274620705z@gmail.com>

fix: typo in Overview.md

---

docs/RoleManagerApi.md

This PR adds python code snippet on RoleManager API docs page for following methods:
- clear
- add_link
- delete_link
- has_link
- print_roles

feat: Add RoleManagerApi Python examples
