- docs/Tutorial.md
Hi,
I found a dead link. This PR fixes it.
Aldair
> Update docs/Tutorial.md - Fix dead link to Argo CD

- docs/ModelStorage.md
Fix: https://github.com/casbin/casbin/issues/279
> Fix initialize model from Go code.

- docs/GetStarted.md
casbin is undefined in case of use import without *
> Nodejs import change

- docs/Overview.md
Fix: https://github.com/casbin/casbin-rs/issues/71
> update casbin-rs status

- docs/Watchers.md
https://github.com/rusenask/casbin-go-cloud-watcher
> Adding gocloud.dev based watcher

- docs/Overview.md
casbin-rs starts to support ABAC via json.
See also: https://github.com/casbin/casbin-rs/issues/78
And the PR related: https://github.com/casbin/casbin-rs/pull/102
@hsluoyz
> check ABAC for casbin-rs

- docs/Tutorial.md
In the mentioned blog post, after reviewing ABAC and the need for a configurable access control system, I've explained the PERM model and an example of using it along with Casbin. I think it will be beneficial for Persian audience of Casbin.
> Update Tutorial.md, add a link to a blog post about PERM model in Persian

- docs/Overview.md
see: https://github.com/casbin/casbin-rs/pull/119
> check filtered adapter for casbin-rs

- docs/ABAC.md
Fix: https://github.com/casbin/casbin-website/issues/78
> Added scaling ABAC rules docs.

- website/static/js/gitter.js
fix: #81 
The screenshots for the fix:
> fix: Top collapse chat button and change color of open change button.

- website/static/css/docusaurus-admonitions.css
> fix: Image size.

- website/static/css/docusaurus-admonitions.css
- website/static/js/code-blocks-buttons.js
> fix: Adding class for features component.

- website/static/css/custom.css
> Fix the bot mobile interface

- docs/ManagementAPI.md
> fix: Batch policy docs for Node.js

- website/static/css/custom.css
Fix: https://github.com/casbin/casbin-website/issues/103
Modify the size to Chat-bot button
> Fix the Chat-bot button size

- docs/Adapters.md
Signed-off-by: Andy Xia <118010339@link.cuhk.edu.cn>
> Add introduction of pymongo adapter

- docs/WebpageController.md
- website/sidebars.json
> add casbin.js doc

- docs/Dispatchers.md
- docs/Watchers.md
- website/sidebars.json
Signed-off-by: dovics <wrs369@163.com>
> add docs for WatcherEx and Dispatcher

- docs/Adapters.md
Replaces Couchbase adapter link with the correct one.
> Fixes Couchbase adapter link

- docs/RBAC.md
- docs/WebpageController.md
Signed-off-by: kingiw <kingiw@hotmail.com>
> Fix broken link in Casbin.js, add instructions.

- docs/RBAC.md
Signed-off-by: 00LT00 <lightning@zerokirin.online>
casbin/casbin#600
> fix: update rbac.md

- docs/LogError.md
Signed-off-by: dovics <wangrushen369@gmail.com>
Fix: https://github.com/casbin/casbin/issues/616
> fix: remove err handling outdate docs

- docs/LogError.md
> docs: Update LogError.md

- docs/LogError.md
- netlify.toml
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
> docs: update log document

- docs/Function.md
Fix: https://github.com/casbin/casbin-website/issues/149
> docs: add docs for keyGet and keyGet2

- docs/LogError.md
Refer to: https://github.com/casbin/pycasbin/pull/80#issuecomment-766851042
add a section to the notes for pycasbin logging considerations
> pycasbin logging notes

- docs/ManagementAPI.md
Fix: https://github.com/casbin/casbin/issues/613
> add: add some management api

- .github/workflows/node-ci.yml
- .github/workflows/pr_ci.yml
- docs/ManagementAPI.md
Fix: https://github.com/casbin/casbin/issues/606
> add management docs and pr ci

- docs/Dispatchers.md
Fix: https://github.com/casbin/casbin/issues/547
> add some docs

- docs/ManagementAPI.md
- docs/PolicySubsetLoading.md
Fix: https://github.com/casbin/casbin/issues/560
> add LoadIncrementalFilteredPolicy docs

- docs/Watchers.md
Fix: https://github.com/casbin/casbin/issues/712
> add more docs for WatcherEx

- docs/AdminPortal.md
RESTful API gateway based on ThinkPHP + ORM + JWT + RBAC (Casbin)
> RESTful API gateway based on ThinkPHP + ORM + JWT + RBAC (Casbin)

- docs/APITutorial.md
- website/sidebars.json
Signed-off-by: Kininaru <shiftregister233@outlook.com>
added link to the sidebar
added the page to the website
added RBAC APIs and deleted Function APIs
fixed typo error
fixed a typo error
fixed a typo error
> added a tutorial for APIs

- docs/Function.md
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
> docs: add globMatch doc

- docs/CasbinRBACAndRBAC96.md
- website/sidebars.json
Fix: https://github.com/casbin/casbin-website/issues/4
> added Casbin RBAC and RBAC96

- docs/WebpageController.md
Fix: https://github.com/casbin/casbin-website/issues/174
> Fix: Error document

- docs/APITutorial.md
Fix: https://github.com/casbin/casbin-website/issues/82
changed the title of the origin PR to this one, and removed some error signoffs in the origin PR.
Signed-off-by: Kininaru <shiftregister233@outlook.com>
> added details about EnforceEx()

- docs/GetStarted.md
- docs/Tutorial.md
In this PR, I add some new instructions for beginners in `GetStarted.md` to make it more reader-friendly. Besides, I fix some little problem in `Tutorial.md `
> Fix GetStarted.md and add some new instructions for beginners

- docs/RoleManagerApi.md
- docs/RoleManagers.md
- website/sidebars.json
Fix: https://github.com/casbin/casbin-website/issues/180
> add: docs for role manager

- docs/CasbinRBACAndRBAC96.md
- docs/RBAC.md
> Fix issue #184 and #183

- docs/Tutorial.md
I am the author of the blog post and my website has moved to a new domain.
> Update link to one of the tutorials

- docs/data-permissions.md
- website/sidebars.json
Fix: https://github.com/casbin/casbin-website/issues/187
In this PR, I fixed issue #187 . Add a new page called data-permissions and add some content in it.
I am sorry for coming late. Since 8 days ago I comment in the issue #187 . Because I am a little confused about the content I am going to deal with here. So I tried to read some tutorials about casbin. And now I opened this PR. If I have done something wrong in this PR, please tell me and I will learn from it. Thanks.
> Fix issue#187, add a new page data-permissions

- docs/SuperAdmin.md
- website/sidebars.json
> docs: Add a page for super admin usage

- docs/Effector.md
- website/sidebars.json
Fix: https://github.com/casbin/casbin-website/issues/202
> docs: Add the new effector to official docs

- docs/Overview.md
- docs/SyntaxForModels.md
Fix: https://github.com/casbin/casbin-website/issues/191
> docs: Describe the "in" operator in matcher grammar

- docs/Effector.md
- docs/RBAC.md
- website/sidebars.json
Fix: #110 
@hsluoyz plz review
> docs: Improve the docs for RBAC pattern matching

- docs/RBACWithDomainsAPI.md
- website/sidebars.json
Signed-off-by: closetool <4closetool3@gmail.com>
For: https://github.com/casbin/casbin/pull/784#issuecomment-832527985
> docs: rbac with domains api

- docs/WebpageController.md
fix: https://github.com/casbin/casbin.js/issues/58
> feat: add explanation for casbin.js auto mode

- docs/GetStarted.md
Add **Get Roles** API in **Get Started** docs for Delphi
Fix: https://github.com/casbin4d/Casbin4D/issues/10
> docs: Add rolesForEntity API for Get Started docs

- docs/Watchers.md
- website/pages/en/index.js
The repositories have been moved to the new GitHub organization. We decided to bring them together.
> Ruby versions have been moved to new organization.

- docs/RBACWithDomainsAPI.md
Signed-off-by: ErikQQY <2283984853@qq.com>
Fix: #221
> docs: Add naming convention to docs

- docs/CloudNative.md
- website/sidebars.json
Signed-off-by: ErikQQY <2283984853@qq.com>
> docs: Add cloud native docs

- docs/RBACAPI.md
Signed-off-by: closetool <4closetool3@gmail.com>
Fix: casbin/casbin#798
> docs: add GetImplicitResourcesForUser and GetImplicitUsersForRole

- docs/SyntaxForModels.md
Signed-off-by: closetool <4closetool3@gmail.com>
Fix: #231
> docs: add doc for "in"

- docs/ManagementAPI.md
> docs: add doc for fieltered api

- website/pages/en/index.js
- website/static/css/code-blocks-buttons.css
> feat: Add small logo icons at the left of each button

- docs/Adapters.md
> docs: add adapter specification

- docs/K8sAuthz.md
Signed-off-by: Ashish Malik <b218008@iiit-bh.ac.in>
Made few changes related to the PR-  [#12](https://github.com/casbin/k8s-authz/pull/12)
> docs: updates for the support of all resources

- .github/workflows/node-ci.yml
Fix: #250 
Fix: #247 
Signed-off-by: ErikQQY <2283984853@qq.com>
> fix: Fix Crowdin failing

- docs/Adapters.md
Signed-off-by: smrpn <samarpan_d@pp.iitr.ac.in>
> feat: add json-adapter to docs

- docs/PriorityModel.md
- docs/SupportedModels.md
- docs/SyntaxForModels.md
> feat: add "subjectPriority(p.eft) || deny" feature

- docs/ABAC.md
> docs: add docs for policy file escape

- docs/PriorityModel.md
Signed-off-by: Edmond <edomondja@gmail.com>
> fix: Add data at subject_priority_policy.csv

- docs/SyntaxForModels.md
associate feature: [casbin#838](https://github.com/casbin/casbin/pull/838)
> feat: add multiple type useage to doc

- docs/EnvoyAuthz.md
- docs/K8sAuthz.md
- website/sidebars.json
Signed-off-by: Ashish Malik <b218008@iiit-bh.ac.in>
> docs: Added docs of Envoy Authz

- docs/GetStarted.md
Signed-off-by: Edmond <edomondja@gmail.com>
> feat: add Lua example about permission management

- website/blog/2021-08-19-apisix-casbin-authorization.md
This is similar to the previously written blog post, does this need any changes?
> docs: added blog post to introduce authz-casbin plugin

- docs/MultiThreading.md
Reference: casbin/casbin-cpp#147
> docs: Added docs on multithreading for casbin-cpp

- docs/PolicyStorage.md
> feat: add detailed policy storage description

- docs/Contributing.md
- website/sidebars.json
- website/siteConfig.js
Signed-off-by: ErikQQY <2283984853@qq.com>
> docs: Add contributing page

- docs/RBAC.md
Fix: https://github.com/casbin/casbin/issues/885
> feat: add more details about domain pattern in RBAC

- docs/PolicyStorage.md
fix: [casbin#886](https://github.com/casbin/casbin/issues/886)
> feat: add the use of commas in policy storage

- docs/RBAC.md
> fix: simplify the use of "AddDomainMatchingFunc"

- docs/SyntaxForModels.md
feat: Multiple sections type for node.js
> feat: Multiple sections type for node.js

- docs/SyntaxForModels.md
Together with: https://github.com/casbin/casbin/pull/896
> fix: EnforceContext members variable name lowercase leads to private

- docs/Adapters.md
> feat: Add adapter conversion instructions

- docs/RBACWithDomainsAPI.md
https://github.com/casbin/casbin.js/pull/211
> docs: RBAC with Domains API for casbin.js 1

- docs/PriorityModel.md
Fix: https://github.com/casbin/casbin/issues/930
> Change the limit description of priority

- docs/DataPermissions.md
- docs/GetStarted.md
- docs/ManagementAPI.md
- docs/Overview.md
- docs/RBACAPI.md
- docs/RBACWithDomainsAPI.md
- docs/SyntaxForModels.md
- docs/Watchers.md
Signed-off-by: Yixiang Zhao <seriouszyx@foxmail.com>
> feat: add jcasbin docs

- docs/ManagementAPI.md
- docs/RBACAPI.md
- fixes #294 
- Added **Node.js** examples for **Management API** & **RBAC API**.
> fix: Updated Management API & RBAC API for Node.js 

- docs/DataPermissions.md
- docs/ManagementAPI.md
- docs/RBACAPI.md
- #300 
- Add Node.js example for BatchEnforce、
Fix: https://github.com/casbin/casbin-website/issues/300
> feat: Added Node.js example for BatchEnforce

- docs/Adapters.md
Fix: https://github.com/casbin/pycasbin/issues/245
> Added Async ormar Adapter

- docs/SyntaxForModels.md
Signed-off-by: stonex <1479765922@qq.com>
> Add evaluator for casbin-cpp

- docs/Enforcers.md
- website/sidebars.json
Fix: https://github.com/casbin/casbin-website/issues/310
> feat: Add enforcer

- docs/RBAC.md
- docs/RoleManagerApi.md
Fix: https://github.com/casbin/node-casbin/issues/298
> fix: Add Node.js example for Matching Function & RoleManagerAPI

- docs/RBACWithDomainsAPI.md
Fix: https://github.com/casbin/casbin/pull/974#issuecomment-1079647458
> feat: Add RBAC API for GetAllDomains

- docs/Benchmark.md
- docs/SyntaxForModels.md
Signed-off-by: stonex <1479765922@qq.com>
+ Link to [this issue](https://github.com/casbin/casbin-cpp/issues/176)
> fix: fix casbin-cpp evaluator and benchmarks data.

- README.md
https://casbin.org/docs/zh-CN/abac
> fix: Fix some translation and formatting issues

- .github/workflows/node-ci.yml
> ci: fix unsafe repository error

- .github/workflows/node-ci.yml
Fix: https://github.com/casbin/casbin-website/issues/323
> ci: update crowdin action to 1.4.8

- docs/ManagementAPI.md
Fixed some Rust and Go examples, and some indentation.
> Fix Go and Rust examples

- docs/GetStarted.md
This PR adds SQL PythonPython code example on Getting Started page
> feat: Add SQL Python Getting Started example

- docs/ManagementAPI.md
This PR adds AddFunction python code snippet on ManagementAPI docs page, and fix some typos on Enforcer methods
> fix: Add AddFunction python code snippet

- docs/ManagementAPI.md
This PR adds AddFunction nodejs code snippet on ManagementAPI docs page
It fixes one item of issue #306
> fix: Add addFunction nodejs code example #306

- docs/ManagementAPI.md
This PR adds loadFilteredPolicy python code snippet on ManagementAPI docs page
> feat: Add load_filtered_policy python  code example

- docs/ManagementAPI.md
This PR adds "LoadIncrementalFilteredPolicy" python code snippet on Management API docs page.
> feat: Add LoadIncrementalFilteredPolicy python code snippet

- website/pages/en/index.js
- website/pages/en/users.js
> fix: Make index page can be translated

- website/pages/en/help.js
- website/pages/en/index.js
> fix: Make index and help page can be translated

- docs/Overview.md
This PR adds "in" matcher as available for Node.js on docs/Overview page
It fixes one item of issue #306
> fix: Fix overview feature nodejs #306

- website/pages/en/index.js
Fix: https://github.com/casbin/casbin-website-v2/issues/50
> feat: Add a banner to tell people to visit v2 site

- website/pages/en/index.js
- website/siteConfig.js
- website/static/css/custom.css
- website/static/js/banner.js
> feat: Add a announcementBar
